# Form implementation generated from reading ui file 'main_chatWIndow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import os
import threading
import time
from multiprocessing import Process

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import Qt
from PyQt6.QtGui import QPalette, QColor, QTextCursor
from PyQt6.QtWidgets import QWidget, QApplication, QMessageBox, QMainWindow

import net.networkmanager
from gui import changeNameWindow
from net import networkmanager
from net.networkmanager import Networkmanager
from settings import settings


class Ui_MainWindow(QWidget):
    def __init__(self):
        super().__init__()
        #netm = Networkmanager()
        networkmanager.run_daemon()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 675)
        MainWindow.setMinimumSize(QtCore.QSize(838, 0))
        MainWindow.setMaximumSize(QtCore.QSize(4048, 4048))

        MainWindow.closeEvent = self.closeEvent

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        self.userChat = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userChat.setObjectName("userChat")
        self.gridLayout.addWidget(self.userChat, 1, 0, 1, 2)
        self.userChat.returnPressed.connect(self.send)

        self.chatButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.chatButton.setAutoDefault(True)
        self.chatButton.setObjectName("chatButton")
        self.gridLayout.addWidget(self.chatButton, 1, 2, 1, 1)
        self.chatButton.clicked.connect(self.send)

        self.userList = QtWidgets.QListView(parent=self.centralwidget)
        self.userList.setObjectName("userList")
        self.gridLayout.addWidget(self.userList, 0, 1, 1, 2)

        self.chatBox = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.chatBox.setObjectName("chatBox")
        self.gridLayout.addWidget(self.chatBox, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1026, 22))
        self.menubar.setObjectName("menubar")
        self.menuEinstellungen = QtWidgets.QMenu(parent=self.menubar)
        self.menuEinstellungen.setObjectName("menuEinstellungen")
        self.menuBeenden = QtWidgets.QMenu(parent=self.menubar)
        self.menuBeenden.setObjectName("menuBeenden")
        self.menuHilfe = QtWidgets.QMenu(parent=self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.changeName = QtGui.QAction(parent=MainWindow)
        self.changeName.setObjectName("changeName")
        self.changeName.triggered.connect(self.openNameChangeWindow)

        self.action_ber_FlowChatPy = QtGui.QAction(parent=MainWindow)
        self.action_ber_FlowChatPy.setObjectName("action_ber_FlowChatPy")
        self.actionFenster_Fokusieren = QtGui.QAction(parent=MainWindow)
        self.actionFenster_Fokusieren.setCheckable(True)
        self.actionFenster_Fokusieren.setObjectName("actionFenster_Fokusieren")
        self.actionDunkle_Ansicht = QtGui.QAction(parent=MainWindow)
        self.actionDunkle_Ansicht.setCheckable(True)
        self.actionDunkle_Ansicht.setObjectName("darkMode")

        self.menuEinstellungen.addAction(self.changeName)
        self.menuEinstellungen.addAction(self.actionFenster_Fokusieren)
        self.menuEinstellungen.addAction(self.actionDunkle_Ansicht)
        self.menuHilfe.addAction(self.action_ber_FlowChatPy)
        self.actionDunkle_Ansicht.triggered.connect(self.change_theme)

        self.menuEinstellungen.addAction(self.changeName)
        self.menuEinstellungen.addAction(self.actionFenster_Fokusieren)
        self.menuEinstellungen.addAction(self.actionDunkle_Ansicht)

        self.menubar.addAction(self.menuEinstellungen.menuAction())
        self.menubar.addAction(self.menuBeenden.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())
        #self.menuBeenden.triggered.connect(self.closeEvent(MainWindow.closeEvent))

        self.retranslateUi(MainWindow)

        self.change_theme_color()

        self.recv = threading.Thread(target=self.poll_for_new_messages)
        self.recv.start()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # defines what happens when you close the window
    def closeEvent(self, event):
        qmsgbox = QMessageBox()
        reply = qmsgbox.question(MainWindow, "Beenden", "Willst du FlowChatPy wirklich beenden?",
                                 qmsgbox.standardButtons().Yes, qmsgbox.standardButtons().No)
        # confirmation box
        if reply == qmsgbox.standardButtons().Yes:
            event.accept()
            # closes sockets
            net.networkmanager.on_closing()
            # stops all threads and shuts down the application on close
            os._exit(0)
        else:
            event.ignore()

    def openNameChangeWindow(self):
        changeNameWindow.ChangeNameWindow = changeNameWindow.ChangeNameWindow()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlowChatPy"))
        self.chatButton.setText(_translate("MainWindow", "Senden"))
        self.menuEinstellungen.setTitle(_translate("MainWindow", "Einstellungen"))
        self.menuBeenden.setTitle(_translate("MainWindow", "Beenden"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.changeName.setText(_translate("MainWindow", "Namen ändern"))
        self.actionFenster_Fokusieren.setText(_translate("MainWindow", "Fenster fokussieren"))
        self.actionDunkle_Ansicht.setText(_translate("MainWindow", "Darkmode"))
        self.action_ber_FlowChatPy.setText(_translate("MainWindow", "Über FlowChatPy"))

    def send(self, *args):
        net.networkmanager.send_message(self.userChat.text())
        self.userChat.setText("")

    def change_theme(self, changedSettings):
        if self.actionDunkle_Ansicht.isChecked():
            settings.settingsInstance.dark_mode = True
        else:
            settings.settingsInstance.dark_mode = False
        settings.settingsInstance.save()
        self.change_theme_color()

    def change_theme_color(self):
        palette = QPalette()
        if settings.settingsInstance.dark_mode:
            palette.setColor(QPalette.ColorRole.Window, QColor(48, 48, 45))
            palette.setColor(QPalette.ColorRole.Base, Qt.GlobalColor.black)
            palette.setColor(QPalette.ColorRole.Text, QColor(0, 255, 0))
            palette.setColor(QPalette.ColorRole.ButtonText, Qt.GlobalColor.black)
        else:
            palette = QPalette()
            palette.setColor(QPalette.ColorRole.Window, Qt.GlobalColor.lightGray)
            palette.setColor(QPalette.ColorRole.Base, Qt.GlobalColor.white)
            palette.setColor(QPalette.ColorRole.Text, Qt.GlobalColor.black)
            palette.setColor(QPalette.ColorRole.ButtonText, Qt.GlobalColor.black)
        app.setPalette(palette)

    def poll_for_new_messages(self):
        while True:
            time.sleep(0.1)
            # In case new messages are found in the message_queue:
            if net.networkmanager.message_queue:
                for messagepayload in net.networkmanager.message_queue:
                    # Get message payload
                    payload = json.loads(messagepayload)
                    if "type" in payload is None:
                        continue

                    payloadtype = payload["type"]
                    message = None

                    if payloadtype == "customMessage":
                        message = payload["message"]

                    if payloadtype == "userMessage":
                        # format the payload to print as a readable message format
                        message = payload["date"] + payload["name"] + " : " + payload["message"]

                    if message is not None and payload["message"] != "":
                        self.chatBox.append(message)
                        # Scrolled automatisch zu einer neuen Nachricht
                        self.chatBox.moveCursor(QTextCursor.MoveOperation.End)

                    # remove message from message_queue
                    net.networkmanager.message_queue.remove(messagepayload)

                    if payloadtype == "command":
                        print("@TODO Command")


import sys

app = QApplication(sys.argv)
MainWindow = QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec())

# if __name__ == "__main__":
#    import sys
#    app = QApplication(sys.argv)
#    MainWindow = QMainWindow()
#    ui = Ui_MainWindow()
#    ui.setupUi(MainWindow)
#    MainWindow.show()
#    sys.exit(app.exec())
